spring.application.name=cafe.project

<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/testing_cafe
=======
spring.datasource.url=jdbc:mysql://localhost:3306/cafe_project_db2
>>>>>>> 8cc12fe04d737386f20fe56bfcc777c764f7c7d8
spring.datasource.username=root
spring.datasource.password=12345


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.cache=false


