spring.application.name=cafe.project

spring.datasource.url=jdbc:mysql://localhost:3306/cafe_project_2
spring.datasource.username=root
spring.datasource.password=000681


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.cache=false


