spring.application.name=cafe.project

spring.datasource.url=jdbc:mysql://localhost:3306/cafe_db
spring.datasource.username=root
spring.datasource.password=280523

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.cache=false


